version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-mailer
    environment:
      - TO_EMAIL
    volumes:
      - ./msmtprc.conf:/etc/msmtprc:ro